server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[format_sql]': true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Custom properties for catalog service
catalog:
  service:
    url: "http://localhost:8080/catalog-service/catalog?wsdl"

# Disable security for development
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8080/realms/globalbooks